# Generated by Django 3.1 on 2021-08-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyJobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=200)),
                ('jobdescrption', models.TextField(blank=True, null=True)),
                ('jobStipend', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField()),
                ('accepting', models.BooleanField()),
                ('companyPosted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymodel')),
            ],
            options={
                'order_with_respect_to': 'dateCreated',
            },
        ),
    ]
