# Generated by Django 3.1 on 2021-08-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperince_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('startYear', models.DateField()),
                ('endYear', models.DateField(null=True)),
                ('currently', models.BooleanField()),
                ('studentpro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'order_with_respect_to': 'studentpro',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('studentpro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'order_with_respect_to': 'studentpro',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institue', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('startYear', models.DateField()),
                ('endYear', models.DateField(null=True)),
                ('studying', models.BooleanField()),
                ('studentpro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'order_with_respect_to': 'studentpro',
            },
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCertificate', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('certificateYear', models.DateField()),
                ('linkCertificate', models.URLField(null=True)),
                ('studentpro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'order_with_respect_to': 'studentpro',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAward', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('awardYear', models.DateField()),
                ('linkAward', models.URLField(null=True)),
                ('studentpro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'order_with_respect_to': 'studentpro',
            },
        ),
    ]
