# Generated by Django 3.2.6 on 2021-09-28 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_award_certification_education_skills_workexperince_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.CharField(blank=True, default=911234567891, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
