# Generated by Django 3.1 on 2021-09-29 17:37

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d', validators=[student.validators.validate_file_extension]),
        ),
    ]
