# Generated by Django 3.2.6 on 2021-09-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210805_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.BooleanField(choices=[(False, 'Student'), (True, 'Company')], default=False),
        ),
    ]
